---
title: "Lab 1 Sample Practise"
output: html_notebook
---
assign and print a variable
```{r}
x<-1
print(x)
```
```{r}
x
```
```{r}
msg="hello"
msg
```
```{r}
typeof(x)
```
```{r}
typeof(msg)
```
explicit and implicit printing
```{r}
x<-1:20
print(x)
x
```
```{r}
rollNo<-1:70
rollNo
```
```{r}
y<-20:30
y
```
```{r}
x<-c(0.5,0.6)
x
```
```{r}
x<-c(TRUE,FALSE)
x
```
```{r}
x<-c(T,F)
x
```
```{r}
x<-c("a","b","c")
x
```
```{r}
x=9:29
x
```
```{r}
x=c(1+0i,2+4i)
x
```
```{r}
x<-vector("numeric",length=10)
x
```
to get help
```{r}
?type
```
```{r}
help(type)
```

```{r}
y1<-c(1.7,"a")
y1
```
```{r}
y2=c(TRUE,2)
y2
```
```{r}
y3<-c("a",TRUE);y3
```
```{r}
class(y1)
class(y2)
class(y3)
```
```{r}
y11<-c(1.7,"3.2")
y11
class(y11)
```
```{r}
y22<-c(FALSE,TRUE)
y22
class(y22)
```

-------------------------
Explicit Coercion
-------------------------
```{r}
x<-0:6
x
class(x)
```
```{r}
y=as.numeric(x)
y
class(y)
```
```{r}
z=as.character(x)
z
class(z)
```
```{r}
l=as.logical(x)
l
class(l)
```
```{r}
com=as.complex(x)
com
class(com)
```
```{r}

```

